version: 2.1

commands:
  brew-install:
    description: "Brew install MacOS dependencies (or restore from cache)"
    steps:
      - run: make install-dependencies
  build-and-test:
    steps:
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror"
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" test
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" check
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" demoGraphics

jobs:
  build-macos:
    macos:
      xcode: "26.5"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - brew-install
      - build-and-test

workflows:
  build_and_test:
    jobs:
      - build-macos
