name: Build Docker Build Env

on:
  workflow_dispatch:
    inputs:
      buildEnv:
        description: Image to rebuild
        required: true
        type: choice
        options:
          - arch
          - clang
          - gcc
          - mingw

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    env:
      buildEnv: ${{ inputs.buildEnv }}

    steps:
      - uses: actions/checkout@v6

      - name: Docker build
        run: make build-image-${{ env.buildEnv }}

      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username "${{ github.repository_owner }}" --password-stdin

      - name: Docker push
        run: make push-image-${{ env.buildEnv }}
