name: Build Docker Build Env

on:
  workflow_dispatch:
    inputs:
      buildEnv:
        description: Image to rebuild
        required: true
        type: choice
        options:
          - arch
          - clang
          - gcc
          - mingw
      multiPlatform:
        description: Multi-platform build
        required: true
        type: boolean
        default: false
  workflow_call:
    inputs:
      buildEnv:
        required: true
        type: string

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    env:
      buildEnv: ${{ inputs.buildEnv }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Docker
        if: ${{ inputs.multiPlatform }}
        uses: docker/setup-docker-action@v5
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        if: ${{ inputs.multiPlatform }}
        uses: docker/setup-qemu-action@v4

      - name: Docker build (multi-platform)
        if: ${{ inputs.multiPlatform }}
        run: make multi-build-image-${{ env.buildEnv }}

      - name: Docker build
        if: ${{ !inputs.multiPlatform }}
        run: make build-image-${{ env.buildEnv }}

      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username "${{ github.repository_owner }}" --password-stdin

      - name: Docker push
        run: make push-image-${{ env.buildEnv }}
